spring.application.name=spinnex

# Database Configuration with flexible environment variables
# If DB_URL, DB_USER, or DB_PASSWORD are not found in the system, it drops back to your Render database directly.
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8e6ko6k1jcs739ls5u0-a.singapore-postgres.render.com/spinnex_dev}
spring.datasource.username=${DB_USER:spinnex_dev_user}
spring.datasource.password=${DB_PASSWORD:W7hpL4QQoOYssdk7Cg4VGlCOvkSXP0Je}

# JPA / Hibernate Properties for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Dynamic port handling required by Render (defaults to 8080 locally)
server.port=${PORT:8080}